<a href="https://colab.research.google.com/github/shannonshih/Tibame_GAD245-Practice-HW_0217/blob/main/0_Scikit_learn_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-learn 介紹

Scikit-learn（簡稱 sklearn）是一個用於資料挖掘和資料分析的機器學習庫，主要使用 Python 語言編寫。它提供了許多簡單且高效的工具，適用於資料預處理、特徵工程、模型訓練、模型評估以及模型調整等任務。Scikit-learn 是基於 NumPy、SciPy 和 matplotlib 等庫構建的，這使得它能夠與這些科學計算庫無縫整合。

## 主要功能

1. **分類（Classification）**
   - 例如支持向量機（SVM）、決策樹、隨機森林、K近鄰（KNN）等模型，用於將資料分配到不同的類別。

2. **回歸（Regression）**
   - 例如線性回歸、嶺回歸、Lasso 回歸等模型，用於預測連續的數值。

3. **聚類（Clustering）**
   - 例如 K-means、DBSCAN 等演算法，用於將資料點劃分為多個簇。

4. **降維（Dimensionality Reduction）**
   - 例如主成分分析（PCA）等技術，用於降低資料的特徵數量。

5. **模型選擇和評估（Model Selection and Evaluation）**
   - 提供交叉驗證、網格搜尋等工具，幫助選擇最佳的模型和參數。

6. **資料預處理（Preprocessing）**
   - 提供標準化、歸一化、編碼等多種資料處理方法。

## 優點

- **簡單易用**：適合初學者和快速實現原型。
- **豐富的文檔與社群支持**：擁有詳盡的官方文檔及大量的教學資源。
- **與科學計算庫無縫整合**：基於 NumPy、SciPy 和 matplotlib，適合用於學術和研究項目。

## 使用場景

Scikit-learn 非常適合用於教育、研究及小型到中型的機器學習專案，能夠快速實現和測試各種機器學習演算法。

## 參考

* https://scikit-learn.org/
* https://scikit-learn.org/stable/user_guide.html
* https://scikit-learn.org/stable/auto_examples/index.html
* https://scikit-learn.org/stable/api/index.html

In [ ]:
# 安裝套件
# ! pip install scikit-learn

# Quick Start

In [1]:
import numpy as np
from sklearn.datasets import load_iris

# 載入 Iris 資料集
iris = load_iris()
X = iris.data  # 特徵
y = iris.target  # 標籤

In [2]:
from sklearn.model_selection import train_test_split
# 資料集分割：將資料集分成訓練集和測試集，80% 用於訓練，20% 用於測試
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [4]:
# 選擇一個分類模型
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC

# model = KNeighborsClassifier(n_neighbors=3)
model = MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)
# model = SVC(kernel='rbf', random_state=42)

In [5]:
# 訓練模型
model.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(10,), max_iter=1000, random_state=42)

In [6]:
# 預測
y_pred = model.predict(X_test)

In [7]:
# 評估
from sklearn.metrics import classification_report, confusion_matrix

# 顯示分類報告和混淆矩陣
print("分類報告：")
print(classification_report(y_test, y_pred))

print("混淆矩陣：")
print(confusion_matrix(y_test, y_pred))


分類報告：
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

混淆矩陣：
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
